### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by cbesix1998** [alandtse/Buffout4#14]
Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF710C838F0 Fallout4.exe+1B938F0	mov eax, [rcx+0x0C] |  BSResourceNiBinaryStream::BSResourceNiBinaryStream(BSTSmartPointer<BSResource::Stream,BSTSmartPointerIntrusiveRefCount>&,bool,bool)_1B938F0)

Half the mods i install cause this idk what it means

**Comment by alandtse** [comment]
We'd need the full crashlog to do anything. Please post that next time.
