### ISSUE TITLE
Crash on loading save, caused by Buffout4.dll?

### ISSUE THREAD

**Issue by PureVanilla18** [alandtse/Buffout4#15]
Crash log says:

Main Error: Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF85D49B330 Buffout4.dll+00FB330	mov byte ptr [rax+0x344], 0x00 
  E:\Documents\source\repos\vcpkg\buildtrees\tbb\src\v2021.8.0-b8941aa9b2.clean\src\tbbmalloc\frontend.cpp:1372 ?freeOwnObject@Block@internal@rml@@QEAAXPEAX@Z)

**Comment by alandtse** [comment]
Thanks. We'd need the full crashlog to process this. Please post that the next time it happens.
