### ISSUE TITLE
REL:/Relocation.h(899) Failed to obtain module handle for: Fallout4.exe

### ISSUE THREAD

**Issue by evildarkarchon** [alandtse/Buffout4#6]
When I try to launch Fallout 4 Flat with version 1.31 of Buffout4 NG I get the error message in the title and f4se.log is attached
It happens both with and without xSE Preloader
[f4se.log](https://github.com/alandtse/Buffout4/files/10830107/f4se.log)

**Comment by such-dev** [comment]
same issue here

**Comment by nikitalita** [comment]
Will be fixed when submodule is updated to https://github.com/alandtse/CommonLibF4/pull/4

**Comment by alandtse** [comment]
Thanks @nikitalita . Should be fixed in 1.31.1
